adding quota check to hortense documentation
hpcleuven/VscDocumentation pull request #236
Opened 2022-01-19 16:33 UTC by kwaegema

2022-01-19 17:16 UTC, itkovian commented on source/gent/tier1_hortense.rst
> +* If you want to check quota for (a) specific project(s), or project(s) that is not listed automatically, use ``-p`` option.
```suggestion
* If you want to check quota for specific projects, or for projects that are not listed automatically, use the ``-p`` option.
```

2022-01-19 17:31 UTC, boegel requested changes

2022-01-19 17:31 UTC, boegel commented on source/gent/tier1_hortense.rst
> +Checking quota
`quota -> `storage quota usage` (same below)

2022-01-19 17:31 UTC, boegel commented on source/gent/tier1_hortense.rst
> +* You can check personal and project quota by running ``my_dodrio_quota``.
```
by running the ``my_dodrio_quota`` command.

2022-01-20 11:03 UTC, itkovian approved these changes

2022-01-20 13:21 UTC, boegel approved these changes

2022-01-20 13:21 UTC, merged