Add page on accessing KU Leuven drives
hpcleuven/VscDocumentation pull request #295
Opened 2023-01-06 15:15 UTC by MaximeVdB

Part of this was already documented, but only in our internal documentation.
I polished that a bit and added info on command-line approaches (`gio` and
`smbclient`).

2023-01-09 10:01 UTC, MaximeVdB commented on source/access/data_transfer_kuleuven_network_drives.rst
> +       gio copy /path/to/local/dir/file.txt smb://unumber@shares.kuleuven.be/drivename/path/to/remote/dir/
That's indeed worth mentioning (done in 0fb260364f97d6709febd8989ca35c369096c744, at the beginning of the page because it applies to all methods).

2023-01-09 10:05 UTC, MaximeVdB commented
> I made one minor comment in-line. Apart from that I have a general remark. I am wondering whether this belongs in the _general_ access section, since it is very specific to our site. I am not sure if there are rules that have been agreed upon, but maybe this new page should go in the _leuven_ subdirectory.

Makes sense -- I moved the page to ``sources/leuven`` (but so keeping the reference to that page in the general `Access and data transfer` page to increase the chances that users actually find out about it).

2023-01-10 16:16 UTC, mselwa requested changes
can -> should?

2023-01-11 07:29 UTC, stevenvdb commented
> > I made one minor comment in-line. Apart from that I have a general remark. I am wondering whether this belongs in the _general_ access section, since it is very specific to our site. I am not sure if there are rules that have been agreed upon, but maybe this new page should go in the _leuven_ subdirectory.
> 
> Makes sense -- I moved the page to `sources/leuven` (but so keeping the reference to that page in the general `Access and data transfer` page to increase the chances that users actually find out about it).

Great. I have already wondered whether adding a page that indexes site-specific pages would be helpful (similar to https://docs.vscentrum.be/en/latest/hardware.html). Now users can only find such pages when using the search function. This is not something that blocks this PR of course.

2023-01-11 07:29 UTC, stevenvdb approved these changes

2023-01-11 10:24 UTC, MaximeVdB commented
> Looks ok. I would probably use more string phrase to say that the drive should be unmounted afterwards instead of "where you can also unmount them afterwards".- > "you should" or "do not forget to". One of the i/o errors 5 was that some drives (personal most likely as well) were mounted on NX systems, so these mounts should not stay forever...

Yes, I've now put more emphasis on the unmounting (https://github.com/hpcleuven/VscDocumentation/pull/295/commits/545bfa86284a52d5ce4d8bfe216edf999eea8b08).

2023-01-24 07:33 UTC, merged