Feature/ondemand kul
hpcleuven/VscDocumentation pull request #335
Opened 2023-08-09 12:58 UTC by w-lampaert

2023-08-09 15:02 UTC, stevenvdb requested changes
Apart from some minor changes, this is ok for me.

Do note that, if I understood correctly, we have been asked to not merge changes into the master branch until https://github.com/hpcleuven/VscDocumentation/pull/334 is completed. Maybe ping @lexming to ask what the status is.

2023-08-11 10:05 UTC, avapirev approved these changes

2023-08-11 10:06 UTC, avapirev approved these changes

2023-09-01 15:24 UTC, jooghe commented
replaced by PR #344

2023-09-01 15:24 UTC, closed without merging