Conda on wICE management - interactive session
hpcleuven/VscDocumentation pull request #355
Opened 2023-09-21 12:09 UTC by StefaanVerwimp

Added short statement in "Conda on wICE" that the interactive Slurm partition can be used for Conda environment management on wICE.

2023-09-22 13:57 UTC, stevenvdb requested changes
The content is ok for me, but to make the link work, you need to put `:ref:` in front of \`interactive Slurm partition on wICE<submit to wice interactive node>\`

2023-09-22 14:22 UTC, stevenvdb approved these changes

2023-09-22 17:17 UTC, moravveji requested changes

2023-09-22 17:17 UTC, moravveji commented on source/leuven/wice_advanced_guide.rst
>  As the operating system and hardware are different on Genius and wICE, we advise
As of monday 25/9/23, the OS of both machines will be identical. So, please update this line, too.

2023-09-22 17:21 UTC, moravveji commented
Furthermore, I like to propose an additional change on paragraph one, sentence 3.
This should totally go away:
"Since the operating system (Rocky Linux) differs from the one on Genius (CentOS), a separate compilation is strictly required in most cases anyway. "

2023-09-25 11:57 UTC, StefaanVerwimp commented
The parts mentioning a difference in operating systems between Genius and wICE have been removed from wice_advanced_guide.rst.

2023-10-04 08:52 UTC, moravveji commented
@StefaanVerwimp : Hey Stefaan. Can you please take another look at my comments and see if we can round off this PR?
Best is that such PRs would not last long. Thanks.

2023-10-06 14:29 UTC, moravveji requested changes

2023-10-06 14:29 UTC, moravveji commented on source/leuven/wice_advanced_guide.rst
> +recommended to compile a version of your code specifically for wICE. A good approach
@StefaanVerwimp : If you could make one last fix, we can have this branch merged.
Is it possible to revisit your PR?
Thanks

2023-10-06 18:22 UTC, moravveji approved these changes
I approve, and will take over afterwards for the last correction.

2023-10-06 18:29 UTC, merged