Increase maximal walltime on KU Leuven debug partitions to 1 hour
hpcleuven/VscDocumentation pull request #429
Opened 2024-08-29 10:23 UTC by stevenvdb

The maximal walltime on debug partitions was increased to 1 hour.

2024-08-29 11:17 UTC, MaximeVdB approved these changes

2024-08-30 06:32 UTC, moravveji requested changes
For the wICE quick start, there is no mention that the maximum number of jobs on the debug queue is only one. This is clearly mentioned for Genius. Could you please push a single sentence covering that, too?

2024-08-30 07:09 UTC, stevenvdb commented
> For the wICE quick start, there is no mention that the maximum number of jobs on the debug queue is only one. This is clearly mentioned for Genius. Could you please push a single sentence covering that, too?

See a972d31cf0c0d9f4c6cec9b42a331c01487d5925

2024-09-03 09:39 UTC, moravveji approved these changes
LGTM

2024-09-05 08:27 UTC, moravveji commented
While this PR is still open, I realized that the second 'Note' box in the [Genius quick start guide](https://docs.vscentrum.be/leuven/genius_quick_start.html) needs to be adjusted too.

2024-09-05 13:03 UTC, stevenvdb commented
> While this PR is still open, I realized that the second 'Note' box in the [Genius quick start guide](https://docs.vscentrum.be/leuven/genius_quick_start.html) needs to be adjusted too.

The second box is about the *default* walltime, not the maximal one. The default walltime has not been changed (of course we could now consider to make 1 hour the default on all partitions for uniformity).

2024-09-06 07:58 UTC, merged