Cloud: Auto-apply variables docs
hpcleuven/VscDocumentation pull request #432
Opened 2024-10-07 12:43 UTC by GoodOldJack12

Updated docs for https://github.com/hpcugent/openstack-templates/pull/21

Requires user communication

2024-11-07 13:30 UTC, alvarosimon commented on source/cloud/terraform.md
> +:::{warning}
I think we can just add this in the email and not in the docs

2024-11-07 13:31 UTC, alvarosimon commented on source/cloud/manage_volumes.md
> +Since DATE, it can also mount and resize them automatically. See {ref}`volumes`
I would remove since... and just say what it does now. We can add this into an email to the current users

2024-11-07 13:32 UTC, alvarosimon commented on source/cloud/terraform.md
> +Automated features like auto-mounting volumes will **not** work on private VMs and are automatically disabled.
This could be confusing for users, at least at this point in the doc, maybe it should be just a note or included later it

2024-11-07 14:13 UTC, alvarosimon commented on source/cloud/terraform.md
> +The latest templates include a module to easily configure an NFS share.
I would include an example in the templates about this and add here  ``cat xxx >> main.tf`` if they want to use it

2024-11-07 14:15 UTC, alvarosimon commented on source/cloud/terraform.md
> +Automated variables will not work if you started using the templates before 11/2024.
I would remove this from the docs as the previous warnings about the template changes. I would include this in the email for the current users not in the doc.

2024-11-07 14:21 UTC, alvarosimon commented on source/cloud/terraform.md
>  ## Deploy Terraform templates
also I would move this section (Deploy Terraform Templates)  at the end, if not users will try to run the commands right now and they should read the rest before doing that

2024-11-07 14:24 UTC, alvarosimon requested changes
@GoodOldJack12 it looks great, I have just some minor comments. I have tried the new templates following the current docs without issues :+1:

2024-11-08 15:37 UTC, wdpypere approved these changes

2024-11-08 15:37 UTC, merged