WIP: adding memory per core info to hardware spec pages
hpcleuven/VscDocumentation pull request #434
Opened 2024-10-09 13:19 UTC by moravveji

In response to a request from user(s) in the user survey of UD2023, in this PR, the information about the default memory per core is added to the following hardware specification pages. 
- genius
- superdome
- wice

2024-10-10 11:42 UTC, moravveji commented
@MaximeVdB : I updated the three pages for genius, superdome and wice and 
- extended/corrected each block where needed. E.g. sometimes newly-defined partition names were missing
- the `gpu_a100_debug` partition is now split from `interactive` partition, because the two have different `DefMemPerCPU`, and in this way, the text is easier to read. Please give this another look.

If we change the `DefMemPerCPU` for the Genius `interactive` partition from 2000MiB to 5000MiB, I have to fix this accordingly.

2024-10-18 12:00 UTC, MaximeVdB requested changes

2024-10-18 12:55 UTC, moravveji commented
> Go ahead, but maybe also check the quickstart page withe the examples of the submit options. To be consistent with the MB or MiB notation.

The accepted units for memory specifications by `sbatch|srun|salloc` commands is e.g. `k|m|g|t`. So, here we do not have the MB vs MiB shenanigans. I checked the quick start pages anyway, and the memory specifications in the examples looked fine to me.

2024-10-18 13:04 UTC, MaximeVdB approved these changes

2024-10-18 14:12 UTC, merged